version: "3.1"

services:
  db:
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: distrupify_test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080